/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.org.apache.xalan.internal.xsltc.compiler.util.StringStack;
import controller.Transaksi;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.DetailPemesanan;
import model.Kurir;
import model.Pegawai;
import model.Pelanggan;
import model.Pemesanan;
import model.Produk;

/**
 *
 * @author HP
 */
public class TransaksiView extends javax.swing.JFrame {
    Transaksi transaksi;
    ArrayList<DetailPemesanan> arrKeranjang;
    Double harga_total;
    /**
     * Creates new form Transaksi
     */
    public TransaksiView() throws SQLException {
        initComponents();
        this.transaksi = new Transaksi();
        this.arrKeranjang = new ArrayList<>();
        this.harga_total = 0.0;
        this.showComboBoxPelanggan();
        this.showComboBoxPegawai();
        this.showComboBoxKurir();
        this.showComboBoxProduk();
        this.showTableKeranjang();
        this.showTablePemesanan();
    }
    
    private void showComboBoxPelanggan() throws SQLException {
        DefaultComboBoxModel dcbmPelanggan = new DefaultComboBoxModel();
        
        for(Pelanggan p : this.transaksi.getDataPelanggan()){
            dcbmPelanggan.addElement(p.getNama_depan() + " " + p.getNama_belakang());
        }
        
        this.cbPelanggan.setModel(dcbmPelanggan);
    }
    
    private void showComboBoxPegawai() throws SQLException {
        DefaultComboBoxModel dcbmPegawai = new DefaultComboBoxModel();
        
        for(Pegawai p : this.transaksi.getDataPegawai()){
            dcbmPegawai.addElement(p.getNama_depan() + " " + p.getNama_belakang());
        }
        
        this.cbPegawai.setModel(dcbmPegawai);
    }
    
    private void showComboBoxKurir() throws SQLException {
        DefaultComboBoxModel dcbmKurir = new DefaultComboBoxModel();
        
        for(Kurir p : this.transaksi.getDataKurir()){
            dcbmKurir.addElement(p.getNama_perusahaan());
        }
        
        this.cbKurir.setModel(dcbmKurir);
    }
    
    private void showComboBoxProduk() throws SQLException {
        DefaultComboBoxModel dcbmProduk = new DefaultComboBoxModel();
        
        for(Produk p : this.transaksi.getDataProduk()){
            dcbmProduk.addElement(p.getNama_produk() + " Stok (" + p.getStok_produk() + ")");
        }
        this.cbProduk.removeAll();
        this.cbProduk.setModel(dcbmProduk);
    }
    
    private void showTableKeranjang(){
        DefaultTableModel dtmKeranjang = new DefaultTableModel(new String[] {"Nama Produk", "Harga Satuan", "Jumlah", "Diskon"}, 0);
        dtmKeranjang.setRowCount(0);
        
        for(DetailPemesanan dp : this.arrKeranjang){
            dtmKeranjang.addRow(new String[] {dp.getProduk().getNama_produk().toString(), dp.getProduk().getHarga_satuan().toString(), dp.getJumlah().toString(), dp.getDiskon().toString()});
        }
        
        this.tblKeranjang.setModel(dtmKeranjang);
    }
    
    private void showHargaTotal(){
        this.tfTotalHarga.setText(String.valueOf(this.harga_total));
    }
    
    private void showTablePemesanan() throws SQLException{
        DefaultTableModel dtmPemesanan = new DefaultTableModel(new String[] {"Pelanggan", "Pegawai", "Tanggal Pemesanan", "Total Harga"}, 0);
        dtmPemesanan.setRowCount(0);
        
        for(Pemesanan p : this.transaksi.getDataPemesanan()){
            dtmPemesanan.addRow(new String[]{p.getPelanggan().getNama_depan(), p.getPegawai().getNama_depan(), p.getTanggal_pemesanan().toString(), p.getHarga_total().toString()});
        }
        
        this.tblPemesanan.setModel(dtmPemesanan);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbPelanggan = new javax.swing.JComboBox();
        cbPegawai = new javax.swing.JComboBox();
        cbKurir = new javax.swing.JComboBox();
        tfAlamat = new javax.swing.JTextField();
        tfTglPengiriman = new javax.swing.JTextField();
        cbProduk = new javax.swing.JComboBox();
        tfJumlah = new javax.swing.JTextField();
        tfDiskon = new javax.swing.JTextField();
        tfTotalHarga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPemesanan = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDetailPemesanan = new javax.swing.JTextArea();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnLihatDetail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pelanggan");

        jLabel2.setText("Pegawai");

        jLabel3.setText("Kurir");

        jLabel4.setText("Alamat");

        jLabel5.setText("Tgl Pengiriman");

        jLabel6.setText("Produk");

        jLabel7.setText("Jumlah");

        jLabel8.setText("Diskon");

        jLabel9.setText("Harga Total");

        cbPelanggan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbPegawai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbKurir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tfAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlamatActionPerformed(evt);
            }
        });

        cbProduk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tfDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiskonActionPerformed(evt);
            }
        });

        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKeranjang);

        tblPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPemesanan);

        taDetailPemesanan.setColumns(20);
        taDetailPemesanan.setRows(5);
        jScrollPane3.setViewportView(taDetailPemesanan);

        btnTambah.setText("tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnLihatDetail.setText("Lihat Detail");
        btnLihatDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbPegawai, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfTotalHarga, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfAlamat, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbKurir, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfTglPengiriman, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbProduk, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfJumlah, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDiskon, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTambah)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cbPelanggan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnSimpan)
                        .addGap(156, 156, 156)
                        .addComponent(btnLihatDetail)))
                .addGap(94, 94, 94)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(cbPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cbPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cbKurir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(tfTglPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cbProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(tfDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(btnTambah)
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(tfTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSimpan)
                                    .addComponent(btnLihatDetail))
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAlamatActionPerformed

    private void tfDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDiskonActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        Pemesanan pemesanan = new Pemesanan();
        try {
            pemesanan.setPelanggan(this.transaksi.getDataPelanggan().get(this.cbPelanggan.getSelectedIndex()));
            pemesanan.setPegawai(this.transaksi.getDataPegawai().get(this.cbPegawai.getSelectedIndex()));
            pemesanan.setKurir(this.transaksi.getDataKurir().get(this.cbKurir.getSelectedIndex()));
            pemesanan.setTanggal_pemesanan(new Date());
            pemesanan.setTanggal_pengiriman(new SimpleDateFormat("dd/MM/yyyy").parse(this.tfTglPengiriman.getText()));
            pemesanan.setAlamat_pengiriman(this.tfAlamat.getText());
            pemesanan.setHarga_total(this.harga_total);
            pemesanan.setDetail_pemesanan(this.arrKeranjang);
            this.transaksi.insertTransaksi(pemesanan);
            this.showTablePemesanan();
            this.arrKeranjang = new ArrayList<>();
            this.showTableKeranjang();
            this.harga_total = 0.0;
            this.showComboBoxProduk();
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            DetailPemesanan dp = new DetailPemesanan();
            dp.setJumlah(Integer.parseInt(this.tfJumlah.getText()));
            dp.setProduk(this.transaksi.getDataProduk().get(this.cbProduk.getSelectedIndex()));
            
            if(this.tfDiskon.getText().equals("")) {
                dp.setDiskon(Double.parseDouble("0"));
                harga_total += this.transaksi.getDataProduk().get(this.cbProduk.getSelectedIndex()).getHarga_satuan() * Integer.parseInt(this.tfJumlah.getText());
            }else{
                Double diskon = new Double(this.tfDiskon.getText());
                Double totalHargaSebelumDiskon = this.transaksi.getDataProduk().get(this.cbProduk.getSelectedIndex()).getHarga_satuan() * Integer.parseInt(this.tfJumlah.getText());
                Double hargaDiskon = totalHargaSebelumDiskon * diskon;
                dp.setDiskon(diskon);
                harga_total += totalHargaSebelumDiskon - hargaDiskon;    
            }
            this.showHargaTotal();
            this.arrKeranjang.add(dp);
            this.showTableKeranjang();
            this.tfDiskon.setText("");
            this.tfJumlah.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnLihatDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatDetailActionPerformed
        try {
            Pemesanan pemesanan = this.transaksi.getDataPemesanan().get(this.tblPemesanan.getSelectedRow());
            String teks = ""
                    +"===================PELANGGAN==================="+"\n"
                    +"Nama Depan : "+pemesanan.getPelanggan().getNama_depan()+"\n"
                    +"Nama Belakang : "+pemesanan.getPelanggan().getNama_belakang()+"\n"
                    +"Tanggal Lahir : "+new SimpleDateFormat("dd/MM/yyyy").format(pemesanan.getPelanggan().getTanggal_lahir())+"\n"
                    +"Alamat : "+pemesanan.getPelanggan().getAlamat()+"\n"
                    +"Kode Pos : "+pemesanan.getPelanggan().getKode_pos()+"\n"
                    +"No Telp : "+pemesanan.getPelanggan().getNo_telp()+"\n"
                    +"===================PEGAWAI==================="+"\n"
                    +"Nama Depan : "+pemesanan.getPegawai().getNama_depan()+"\n"
                    +"Nama Belakang : "+pemesanan.getPegawai().getNama_belakang()+"\n"
                    +"Tanggal Lahir : "+new SimpleDateFormat("dd/MM/yyyy").format(pemesanan.getPelanggan().getTanggal_lahir())+"\n"
                    +"Alamat : "+pemesanan.getPegawai().getAlamat()+"\n"
                    +"Kode Pos : "+pemesanan.getPegawai().getKode_pos()+"\n"
                    +"No Telp : "+pemesanan.getPegawai().getNo_telp()+"\n"
                    +"===================KURIR==================="+"\n"
                    +"Nama Perusahaan : "+pemesanan.getKurir().getNama_perusahaan()+"\n"
                    +"No Telp : "+pemesanan.getKurir().getNo_telp()+"\n"
                    +"===================PEMESANAN==================="+"\n"
                    +"Tanggal Pemesanan : "+new SimpleDateFormat("dd/MM/yyyy").format(pemesanan.getTanggal_pemesanan())+"\n"
                    +"Tanggal Pengiriman : "+new SimpleDateFormat("dd/MM/yyyy").format(pemesanan.getTanggal_pengiriman())+"\n"
                    +"Alamat Pengiriman : "+pemesanan.getAlamat_pengiriman()+"\n"
                    +"Harga Total : "+pemesanan.getHarga_total()+"\n"
                    +"Produk : "+"\n";
            ArrayList<DetailPemesanan> dp = pemesanan.getDetail_pemesanan();
            for(int i=0; i<dp.size(); i++){
                teks += "\n\n"+(i+1)+". "
                        +"Perusahaan Pemasok : "+dp.get(i).getProduk().getPemasok().getNama_perusahaan()+"\n"
                        +"Alamat Pemasok : "+dp.get(i).getProduk().getPemasok().getAlamat()+"\n"
                        +"Kode Pos Pemasok : "+dp.get(i).getProduk().getPemasok().getKode_pos()+"\n"
                        +"No Telp Pemasok : "+dp.get(i).getProduk().getPemasok().getNo_telp()+"\n"
                        +"Kategori Produk : "+dp.get(i).getProduk().getKategori().getNama_kategori()+"\n"
                        +"Nama Produk : "+dp.get(i).getProduk().getNama_produk()+"\n"
                        +"Harga Produk : "+dp.get(i).getProduk().getHarga_satuan()+"\n"
                        +"Stok Produk : "+dp.get(i).getProduk().getStok_produk()+"\n"
                        +"Jumlah Beli Produk : "+dp.get(i).getJumlah()+"\n"
                        +"Diskon Produk : "+dp.get(i).getDiskon()+"\n";
            }
            this.taDetailPemesanan.setText(teks);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnLihatDetailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TransaksiView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TransaksiView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLihatDetail;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox cbKurir;
    private javax.swing.JComboBox cbPegawai;
    private javax.swing.JComboBox cbPelanggan;
    private javax.swing.JComboBox cbProduk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea taDetailPemesanan;
    private javax.swing.JTable tblKeranjang;
    private javax.swing.JTable tblPemesanan;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfDiskon;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfTglPengiriman;
    private javax.swing.JTextField tfTotalHarga;
    // End of variables declaration//GEN-END:variables

    

    

}
